Implement task2.
Mykola-Kvitka/SoftGame pull request #2
Opened 2022-02-08 15:35 UTC by Mykola-Kvitka

Add iUnit interface.
Implement figts between army.
Implement unittests

2022-02-08 17:18 UTC, elkavitaly requested changes

2022-02-08 17:18 UTC, elkavitaly commented on SoftGame/ArmyFactory.cs
> +        public static IEnumerable<IUnit> UnitsFactoryGeneric<T>(T unit, int count)
I think that all this logic is redundant. You already have a type of class you need to create. Use that type to create the new instance. You don't need to allow passing stings, enums or anything else to the factory. Read about generic type parameter constraints

2022-02-08 17:18 UTC, elkavitaly commented on SoftGame/Battles/Battle.cs
> +            var aliveUnitsArmy1Enumerator = army1.GetAllAliveUnits().GetEnumerator();
Well, maybe this approach is the fastest one, but it looks complicated to understand. I would use LINQ to implement the parts where you're using enumerator.

2022-02-08 17:18 UTC, elkavitaly commented on SoftGame/Skills/Interfaces/IUnit.cs
> +        public int Health {  get; protected set; }
Members of interface are public by default. you don't need to specify access modifiers here explicitly

2022-02-08 17:18 UTC, elkavitaly commented on SoftGame/Skills/Interfaces/IUnit.cs
> +        public double Attack { protected set; get; }
Why is Attack of double type? I didn't see this in requirements

2022-02-08 17:18 UTC, elkavitaly commented on SoftGame/Units/Warrior.cs
> +        protected int Health;
What is the reason of these protected fields if you have the same properties from interface?

2022-02-08 17:18 UTC, elkavitaly commented on SoftGame/Units/Warrior.cs
> +        public object Clone()
Do you know how MemberwiseClone method works? It's not the best approach to copy objects.  In scope of this task you don't need to copy any instances

2022-02-08 17:18 UTC, elkavitaly commented on SoftGame/ArmyFactory.cs
> +        private static List<IUnit> UnitsFactory(string unit, int count)
Don't use switch statements. If you re-think the logic of creating the instances using the generic type parameter, you will not need to use this statement

2022-02-09 11:43 UTC, Mykola-Kvitka commented on SoftGame/ArmyFactory.cs
> +        public static IEnumerable<IUnit> UnitsFactoryGeneric<T>(T unit, int count)
Sasha said that it would be desirable that we could share tests with each other and this implementation was made for this.

2022-02-09 11:49 UTC, Mykola-Kvitka commented on SoftGame/ArmyFactory.cs
> +        private static List<IUnit> UnitsFactory(string unit, int count)
As I wrote earlier, Sasha asked to make it a universal creation of armies.

2022-02-09 11:50 UTC, Mykola-Kvitka commented on SoftGame/Units/Warrior.cs
> +        protected int Health;
Без этого райдер выдает ошибку.

2022-02-09 11:50 UTC, Mykola-Kvitka commented on SoftGame/Units/Warrior.cs
> +        public object Clone()
The use was related to the method of creating a list, but at the moment I have redone and removed the MemberwiseClone .

2022-02-10 08:03 UTC, elkavitaly requested changes

2022-02-10 08:03 UTC, elkavitaly commented on SoftGame/Army.cs
> +        public List<IUnit> GetAllAliveUnits(Expression<Func<IUnit, bool>> predicate)
You don't need to use Expression, because you are working with IEnumerable in memory. It's enough to use just `Func<IUnit, bool>`.
On the other hand, I don't see any reason to use Func as a parameter for a method. The name of your method is _GetAllAliveUnits_, so you need to specify the filter function inside of this method, in other case, any consumer of this method can filter units as it wants. So, it's better to incapsulate the filtering logic in the method

2022-02-10 08:03 UTC, elkavitaly commented on SoftGame/ArmyFactory.cs
> +        public static IEnumerable<IUnit> UnitsFactoryGeneric<T>(T unit, int count)
Nobody has implementation which uses strings or enums now. Because I asked about using types.

2022-02-10 08:03 UTC, elkavitaly commented on SoftGame/Units/Warrior.cs
> +        protected int Health;
It can be related to access modifiers _get_ and _set_ have. Interfaces are not supposed to have any information about implementation and all members should be public. Actually, if you want to use interface you can leave only get accessor in interface, because it's not supposed that anyone outside the class will have an ability to change the health of a warrior. But in class which implements this interface you can specify the _set_ modifier with appropriate access restrictions

2022-02-10 08:03 UTC, elkavitaly commented on SoftGame/Units/Warrior.cs
> +        int IUnit.Health
When property or method has interface name before the actual name, this is called explicit interface implementation. I think, that it may be redundant to use it in scope of this task

2022-02-11 09:11 UTC, elkavitaly requested changes

2022-02-11 09:11 UTC, elkavitaly commented on SoftGame/Skills/Interfaces/IUnit.cs
> +    public abstract class IUnit : IAttacker, IDamageable
Classes has different naming convention

2022-02-11 09:11 UTC, elkavitaly commented on SoftGame/Skills/Interfaces/IUnit.cs
> +        public int Health;
You shouldn't use public fields in classes. This violates encapsulation principle

2022-02-11 09:11 UTC, elkavitaly commented on SoftGame/Units/Warrior.cs
> +        public int Health { get; protected set; }
You don't use fields from your abstract base class. What is the reason of those fields

2022-02-21 17:55 UTC, merged